const systems = {
"Brain":{tone:"Mind / Clarity",summary:"Supports focus, calm thinking, memory rhythm, and mental reset.",foods:["Walnuts","Blueberries","Pumpkin seeds","Dark leafy greens"],drinks:["Rosemary tea","Ginkgo tea","Green tea"],practice:["Brain dump journal","10 minute walk","Single-task for 20 minutes"],inner:["What thought keeps repeating?","What can be simplified today?"]},
"Eyes & Vision":{tone:"Sight / Focus",summary:"Supports eye comfort, visual rhythm, and screen recovery.",foods:["Carrots","Sweet potato","Bilberries or blueberries","Kale"],drinks:["Chrysanthemum tea","Goji berry tea"],practice:["Eye palming","20-20-20 screen breaks"],inner:["What do you need to see clearly?","Soften your gaze."]},
"Lungs":{tone:"Breath / Release",summary:"Supports breath awareness, respiratory comfort, and gentle clearing.",foods:["Pears","Onion","Garlic","Mushroom broth"],drinks:["Mullein tea","Thyme tea","Ginger lemon tea"],practice:["Slow nasal breathing","Steam inhalation","Open chest stretch"],inner:["What grief or pressure needs air?","Exhale longer than you inhale."]},
"Heart":{tone:"Circulation / Emotion",summary:"Supports emotional steadiness, circulation rhythm, and warmth.",foods:["Beets","Berries","Oats","Pomegranate"],drinks:["Hawthorn tea","Hibiscus tea","Cacao tonic"],practice:["Gratitude note","Gentle cardio","Chest opening stretch"],inner:["What does your heart need protected?","What love can you receive?"]},
"Liver":{tone:"Detox Rhythm",summary:"Supports daily processing, bitters, greens, and clean release.",foods:["Dandelion greens","Arugula","Beets","Lemon","Broccoli"],drinks:["Dandelion root tea","Burdock tea","Warm lemon water"],practice:["Twisting stretch","Early light dinner","Declutter one space"],inner:["What are you ready to process?","Release irritability into action."]},
"Spleen":{tone:"Grounding / Nourishment",summary:"Supports grounded energy, warm meals, and stable digestion.",foods:["Squash","Sweet potato","Rice congee","Gingered carrots"],drinks:["Ginger tea","Cinnamon tea"],practice:["Warm breakfast","Slow chewing","Barefoot grounding"],inner:["Where do you need steadiness?","Feed your foundation."]},
"Gut & Digestion":{tone:"Digest / Transform",summary:"Supports digestive rhythm, comfort, fiber, and mindful eating.",foods:["Stewed apples","Fennel","Celery","Fermented vegetables"],drinks:["Peppermint tea","Fennel tea","Ginger tea"],practice:["Walk after meals","Eat without scrolling","Belly breathing"],inner:["What are you still digesting emotionally?","Make space before adding more."]},
"Kidneys & Adrenals":{tone:"Water / Reserve",summary:"Supports hydration, mineral rhythm, rest, and deeper reserves.",foods:["Cucumber","Celery","Seaweed","Black beans","Parsley"],drinks:["Nettle tea","Corn silk tea","Cucumber water"],practice:["Legs up wall","Reduce late caffeine","Slow evening routine"],inner:["Where are you leaking energy?","Protect your reserves."]},
"Reproductive":{tone:"Creation / Flow",summary:"Supports creative energy, pelvic ease, and cyclical awareness.",foods:["Avocado","Sesame","Pumpkin seeds","Raspberry","Dark greens"],drinks:["Raspberry leaf tea","Nettle tea","Ginger tea"],practice:["Hip circles","Creative writing","Warm lower belly compress"],inner:["What wants to be created?","Honor your creative force."]},
"Skin & Lymph":{tone:"Boundary / Flow",summary:"Supports skin clarity, lymph movement, and healthy boundaries.",foods:["Cucumber","Citrus","Parsley","Watermelon","Greens"],drinks:["Calendula tea","Burdock tea","Lemon water"],practice:["Dry brushing","Rebounding or light bounce","Sweat gently"],inner:["What boundary needs care?","Let your surface breathe."]},
"Blood & Circulation":{tone:"Movement / Warmth",summary:"Supports flow, warmth, and clean momentum.",foods:["Beets","Cayenne","Citrus","Leafy greens"],drinks:["Hibiscus tea","Ginger tea","Cinnamon tea"],practice:["Brisk walk","Ankle pumps","Contrast shower"],inner:["Where does life need motion?","Move what has been stuck."]},
"Nervous System":{tone:"Calm / Regulation",summary:"Supports stillness, repair, and gentle rhythm.",foods:["Oats","Magnesium-rich greens","Banana","Sesame"],drinks:["Chamomile tea","Lavender tea","Lemon balm tea"],practice:["Box breathing","Digital sunset","Jaw and neck release"],inner:["What can wait until tomorrow?","Safety first. Softness now."]}
};
const intentions=[["Reset","↻","Begin again. Clear what no longer serves."],["Detox","♨","Release and cleanse. Let go of the old."],["Nourish","🥗","Feed your cells. Restore vitality."],["Calm / Regulate","♡","Find stillness. Return to center."],["Move / Circulate","↗","Awaken energy. Encourage flow."],["Sleep / Recover","☾","Rest deeply. Allow repair."]];
let selectedIntent="Reset", selectedSystem="Eyes & Vision";
const $=id=>document.getElementById(id);
function fillList(id,arr){$(id).innerHTML=arr.map(x=>`<li>${x}</li>`).join("")}
function renderIntentGrid(){ $("intentGrid").innerHTML=intentions.map(i=>`<button class="intentCard ${i[0]===selectedIntent?"active":""}" data-intent="${i[0]}"><div class="icon">${i[1]}</div><h3>${i[0]}</h3><p>${i[2]}</p></button>`).join(""); document.querySelectorAll(".intentCard").forEach(b=>b.onclick=()=>{selectedIntent=b.dataset.intent;renderIntentGrid();renderPlan();document.querySelector("#organ-map").scrollIntoView({behavior:"smooth"})})}
function renderSystem(name){selectedSystem=name;const d=systems[name];$("systemTone").textContent=d.tone;$("systemTitle").textContent=name+" Support Protocol";$("systemSummary").textContent=d.summary;fillList("foodsList",d.foods);fillList("drinksList",d.drinks);fillList("practiceList",d.practice);fillList("innerList",d.inner);document.querySelectorAll(".organDot").forEach(b=>b.classList.toggle("active",b.dataset.system===name));renderPlan()}
function renderPlan(){const d=systems[selectedSystem];$("planMeta").textContent=selectedIntent+" · "+selectedSystem;const plan=[["Eat","Morning · Midday · Evening",d.foods.slice(0,3)],["Drink","Throughout the day",d.drinks.slice(0,2)],["Practice","5–10 minutes",d.practice.slice(0,2)],["Inner Work","Quiet moment",d.inner],["Avoid","All day",["Overloading the system","Skipping water","Ignoring rest signals"]],["Dojo Note","Remember",["Your intention is "+selectedIntent+". Keep it simple and consistent."]]];$("planGrid").innerHTML=plan.map(p=>`<div class="planCard"><p class="eyebrow">${p[1]}</p><h3>${p[0]}</h3><ul>${p[2].map(x=>`<li>${x}</li>`).join("")}</ul></div>`).join("")}
document.querySelectorAll(".organDot").forEach(b=>b.onclick=()=>{renderSystem(b.dataset.system);document.querySelector("#plan").scrollIntoView({behavior:"smooth"})});
document.querySelector(".menuBtn").onclick=()=>document.querySelector(".nav").classList.toggle("open");
$("year").textContent=new Date().getFullYear();renderIntentGrid();renderSystem(selectedSystem);
